emrulmax2/gaslight_new

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/Customers/JobController.php
- app/Http/Controllers/Dashboard.php
- app/Http/Controllers/UserSettings/NumberingController.php
- app/Http/Controllers/UserSettings/ReminderEmailTemplateController.php
- app/Http/Requests/StoreCompanyRequest.php
- app/Models/JobFormPrefixMumbering.php
- database/migrations/2025_02_27_132056_create_job_form_prefix_mumberings_table.php
- database/migrations/2025_02_27_144918_alter_multiple_columns_to_customer_jobs_table.php
- database/seeders/JobFormSeeder.php
- resources/js/app/customers.js
- resources/js/app/jobs.js
- resources/js/app/user-settings/numbering.js
- resources/js/dashboard-modal.js
- resources/views/app/auth/register.blade.php
- resources/views/app/customers/jobs/show-modals.blade.php
- resources/views/app/customers/jobs/tabs/documents-modal.blade.php
- resources/views/app/dashboard/index.blade.php
- resources/views/app/dashboard/modal/index.blade.php
- resources/views/app/settings/index.blade.php
- resources/views/app/settings/numbering/index.blade.php
- resources/views/app/settings/reminders/create.blade.php
- resources/views/app/settings/reminders/index.blade.php
- routes/web.php
- vite.config.js
> 27-02-2025 Updates

- vite.config.js
> Dashboard View Updated

- app/Http/Controllers/Calculator/GasRateCalculator.php
- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/Dashboard.php
- app/Http/Controllers/Jobs/JobController.php
- app/Http/Controllers/Records/RecordController.php
- app/Models/Company.php
- app/Models/Customer.php
- app/Models/CustomerProperty.php
- app/Models/JobForm.php
- database/migrations/2025_03_10_103029_add_type_columns_to_job_forms_table.php
- resources/js/app/calculator/calculator.js
- resources/js/app/jobs/jobs.js
- resources/js/app/records/invoice.js
- resources/js/dashboard-modal.js
- resources/views/app/calculator/index.blade.php
- resources/views/app/dashboard/index.blade.php
- resources/views/app/dashboard/modal/index.blade.php
- resources/views/app/jobs/create.blade.php
- resources/views/app/jobs/index.blade.php
- resources/views/app/records/invoice/index.blade.php
- resources/views/app/records/invoice/modals.blade.php
- routes/web.php
- vite.config.js
> Calculator + Record Structure

- resources/js/app/records/homewoner_gass_safety_record.js
- resources/views/app/records/homeowner_gas_safety_record/index.blade.php
- resources/views/app/records/homeowner_gas_safety_record/modals.blade.php
> Gas Safe Form Update

- app/Http/Controllers/Records/GasServiceRecordController.php
- app/Http/Controllers/Records/GasWarningNoticeController.php
- app/Http/Controllers/Records/HomeOwnerGasSafetyController.php
- app/Http/Controllers/Records/RecordController.php
- app/Models/GasServiceRecord.php
- app/Models/GasServiceRecordAppliance.php
- database/migrations/2025_03_25_095618_create_gas_service_records_table.php
- database/migrations/2025_03_25_095919_create_gas_service_record_appliances_table.php
- database/migrations/2025_03_25_132358_add_certificate_number_column_to_gas_warning_notices_table.php
- resources/css/custom.css
- resources/js/app/records/gas_service_record.js
- resources/js/app/records/gas_service_record_show.js
- resources/views/app/records/gas_service_record/index.blade.php
- resources/views/app/records/gas_service_record/show.blade.php
- resources/views/app/records/gas_warning_notice/index.blade.php
- resources/views/app/records/homeowner_gas_safety_record/show.blade.php
- routes/web.php
- vite.config.js
Warning Notice Certificate & Service Record Notice Partial
> Warning Notice Certificate & Service Record Notice Partial

- app/Http/Controllers/Records/GasBoilerSystemCommissioningChecklistController.php
- app/Http/Controllers/Records/GasBreakdownRecordController.php
- app/Http/Controllers/Records/GasCommissionDecommissionRecordController.php
- app/Http/Controllers/Records/GasPowerFlushRecordController.php
- app/Http/Controllers/Records/GasServiceRecordController.php
- app/Http/Controllers/Records/HomeOwnerGasSafetyController.php
- app/Http/Controllers/Records/RecordController.php
- app/Models/CommissionDecommissionWorkType.php
- app/Models/GasCommissionDecommissionRecord.php
- app/Models/GasCommissionDecommissionRecordAppliance.php
- app/Models/GasCommissionDecommissionRecordApplianceWorkType.php
- database/migrations/2025_04_04_092844_create_commission_decommission_work_types_table.php
- database/migrations/2025_04_04_100123_create_gas_commission_decommission_records_table.php
- database/migrations/2025_04_04_100426_create_gas_commission_decommission_record_appliances_table.php
- database/migrations/2025_04_04_100809_create_gas_commission_decommission_record_appliance_work_types_table.php
- database/seeders/CommissionDecommissionWorkTypeSeeder.php
- database/seeders/DatabaseSeeder.php
- resources/js/app/records/installation_commissioning_decommissioning_record.js
- resources/js/app/records/installation_commissioning_decommissioning_record_show.js
- resources/views/app/records/installation_commissioning_decommissioning_record/index.blade.php
- resources/views/app/records/installation_commissioning_decommissioning_record/show.blade.php
- resources/views/app/records/power_flush_record/index.blade.php
- routes/web.php
- vite.config.js
Power Flush Certificate PDF Done.
> Power Flush Certificate PDF Done.

- app/Http/Controllers/Records/GasUnventedHotWaterCylinderRecordController.php
- app/Http/Controllers/Records/RecordController.php
- app/Models/BoilerManual.php
- app/Models/GasUnventedHotWaterCylinderRecord.php
- app/Models/GasUnventedHotWaterCylinderRecordInspection.php
- app/Models/GasUnventedHotWaterCylinderRecordSystem.php
- database/migrations/2025_04_09_134555_create_gas_unvented_hot_water_cylinder_records_table.php
- database/migrations/2025_04_09_135144_create_gas_unvented_hot_water_cylinder_record_systems_table.php
- database/migrations/2025_04_09_141300_create_gas_unvented_hot_water_cylinder_record_inspections_table.php
- database/seeders/DatabaseSeeder.php
- database/seeders/JobFormNewRows2Seeder.php
- resources/js/app/records/unvented_hot_water_cylinders.js
- resources/js/app/records/unvented_hot_water_cylinders_show.js
- resources/views/app/boiler-brand-and-manual/index.blade.php
- resources/views/app/records/unvented_hot_water_cylinders/index.blade.php
- resources/views/app/records/unvented_hot_water_cylinders/show.blade.php
- routes/web.php
- vite.config.js
Unvented Hot Water Cylinder Record Partial
> Unvented Hot Water Cylinder Record Partial

- app/Http/Controllers/Records/GasBoilerSystemCommissioningChecklistController.php
- app/Http/Controllers/Records/GasBreakdownRecordController.php
- app/Http/Controllers/Records/GasCommissionDecommissionRecordController.php
- app/Http/Controllers/Records/GasJobSheetController.php
- app/Http/Controllers/Records/GasPowerFlushRecordController.php
- app/Http/Controllers/Records/GasServiceRecordController.php
- app/Http/Controllers/Records/GasUnventedHotWaterCylinderRecordController.php
- app/Http/Controllers/Records/GasWarningNoticeController.php
- app/Http/Controllers/Records/HomeOwnerGasSafetyController.php
- app/Http/Controllers/Records/RecordController.php
> Error 3 Issue Fixed.

- app/Http/Controllers/Jobs/JobController.php
- app/Http/Controllers/Records/GasBoilerSystemCommissioningChecklistController.php
- app/Http/Controllers/Records/GasBreakdownRecordController.php
- app/Http/Controllers/Records/GasCommissionDecommissionRecordController.php
- app/Http/Controllers/Records/GasJobSheetController.php
- app/Http/Controllers/Records/GasPowerFlushRecordController.php
- app/Http/Controllers/Records/GasServiceRecordController.php
- app/Http/Controllers/Records/GasUnventedHotWaterCylinderRecordController.php
- app/Http/Controllers/Records/GasWarningNoticeController.php
- app/Http/Controllers/Records/HomeOwnerGasSafetyController.php
- app/Http/Controllers/Records/RecordController.php
- app/Http/Controllers/UserManagementController.php
- resources/js/app/customers/customers.js
- resources/js/app/users/users.js
- resources/views/app/jobs/create.blade.php
- resources/views/app/users/edit.blade.php
- resources/views/app/users/index.blade.php
- resources/views/app/users/modal.blade.php
> Model Type Issue fixed

- vite.config.js
> Vite File Update

- app/Http/Controllers/Api/CompanyController.php
- app/Http/Controllers/Drafts/RecordAndDraftController.php
- app/Http/Controllers/Jobs/JobController.php
- app/Http/Controllers/Records/GasPowerFlushRecordController.php
- app/Http/Controllers/Records/NewRecordController.php
- app/Http/Requests/OccupantDetailsStoreRequest.php
- database/migrations/2025_04_25_083130_alter_column_title_id_to_customer_table.php
- resources/js/app/drafts/certificates.js
- resources/js/app/new-records/create.js
- resources/js/app/new-records/gas-boiler-system-commissioning-checklist.js
- resources/js/app/new-records/gas-breakdown-record.js
- resources/js/app/new-records/gas-safety-record.js
- resources/js/app/new-records/gas-service-record.js
- resources/js/app/new-records/gas-warning-notice-record.js
- resources/js/app/new-records/installation-commissioning-decommissioning-record.js
- resources/js/app/new-records/power-flush-record.js
- resources/js/app/new-records/unvented-hot-water-cylinders.js
- resources/views/app/jobs/create.blade.php
- resources/views/app/jobs/show.blade.php
- resources/views/app/new-records/homeowner_gas_safety_record/index.blade.php
- resources/views/app/new-records/modal.blade.php
- routes/api.php
- routes/web.php
Except Landlord Gas safety Certificate & 2nd Click issue.
> Given issue fixed

- app/Http/Controllers/Customers/CustomerController.php
- app/Http/Controllers/Drafts/RecordAndDraftController.php
- app/Http/Controllers/Records/NewRecordController.php
- app/Http/Controllers/UserManagementController.php
- resources/css/custom.css
- resources/js/app/drafts/certificates.js
- resources/js/app/new-records/create.js
- resources/views/app/drafts/index.blade.php
- resources/views/app/new-records/gas_boiler_system_commissioning_checklist/index.blade.php
- resources/views/app/new-records/gas_breakdown_record/index.blade.php
- resources/views/app/new-records/gas_service_record/index.blade.php
- resources/views/app/new-records/gas_warning_notice/index.blade.php
- resources/views/app/new-records/installation_commissioning_decommissioning_record/index.blade.php
- resources/views/app/new-records/invoice/index.blade.php
- resources/views/app/new-records/job_sheet/index.blade.php
- resources/views/app/new-records/modal.blade.php
- resources/views/app/new-records/power_flush_record/index.blade.php
- resources/views/app/new-records/quote/index.blade.php
- resources/views/app/new-records/unvented_hot_water_cylinders/index.blade.php
- resources/views/app/users/modal.blade.php
Customer Search & Occupants Issue fixed
> Customer Search & Occupants Issue fixed

- app/Http/Controllers/UserSubscriptionWebhookController.php
- app/Models/Company.php
- resources/views/app/company/index.blade.php
Wbhook Pertial + Company Address
> Wbhook Pertial + Company Address

- app/Http/Controllers/CompanyController.php
- app/Http/Controllers/ProfileController.php
- app/Http/Controllers/UserManagementController.php
- app/Http/Controllers/UserSubscriptionWebhookController.php
- app/Http/Middleware/CheckFirstLogin.php
- app/Http/Requests/UpdateProfileNameRequest.php
- app/Http/Requests/UpdateStaffInitalRequest.php
- app/Listeners/SendWelcomeEmail.php
- app/Models/User.php
- app/Models/UserPricingPackage.php
- app/Providers/EventServiceProvider.php
- database/migrations/2025_05_12_094905_add_multiple_columns_to_user_pricing_packages_table.php
- resources/js/app/initial-staff-setup.js
- resources/js/app/users/profile.js
- resources/views/app/dashboard/initial-staff-setup.blade.php
- resources/views/app/profile/index.blade.php
- resources/views/app/user/modal.blade.php
- resources/views/app/users/modal.blade.php
- resources/views/components/themes/icewall/top-bar/index.blade.php
- routes/web.php
- vite.config.js
> Mailing & Staff First Login

- app/Http/Controllers/Api/Customers/CustomerController.php
- app/Http/Controllers/Api/Records/RecordAndDraftController.php
- app/Http/Controllers/Customers/CustomerController.php
- app/Http/Controllers/Customers/CustomerJobAddressController.php
- app/Http/Controllers/Customers/CustomerJobsController.php
- app/Http/Controllers/Dashboard.php
- app/Http/Controllers/Jobs/JobController.php
- resources/js/app/customers/jobs/customer-jobs.js
- resources/js/app/jobs/jobs.js
- resources/views/app/customers/jobs/index.blade.php
- resources/views/app/dashboard/initial-staff-setup.blade.php
- resources/views/app/jobs/index.blade.php
- routes/api.php
API & Job Status Modifications
> API & Job Status Modifications

- resources/js/app/companies.js
> Company JS Issue Fixed

- app/Http/Controllers/Api/Auth/LoginController.php
- app/Http/Controllers/Api/Auth/RegisteredUserController.php
- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/Customers/CustomerController.php
- app/Models/RegistrationOtp.php
- app/Models/User.php
- app/Models/UserOtp.php
- database/migrations/2025_09_16_094734_create_registration_otps_table.php
- database/migrations/2025_09_16_104207_add_mobile_number_column_to_users_table.php
- database/migrations/2025_09_17_092049_create_user_otps_table.php
- database/migrations/2025_09_17_133906_add_expire_at_column_to_registration_otps_table.php
- resources/css/custom.css
- resources/images/flags/uk.svg
- resources/js/app/otp-login.js
- resources/js/app/register.js
- resources/views/app/auth/login-email.blade.php
- resources/views/app/auth/register.blade.php
- resources/views/app/customers/create.blade.php
- resources/views/app/customers/edit.blade.php
- resources/views/pages/wizard-layout-3.blade.php
- routes/api.php
- routes/web.php
- vite.config.js
> Login & Register with OTP

- resources/js/app/otp-login.js
- resources/js/app/register.js
- resources/views/app/auth/register.blade.php
> Register Issue fixe

- resources/js/app/register.js
> Js Issue fixed

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Models/RegistrationOtp.php
- resources/js/app/register.js
- resources/views/app/auth/register.blade.php
> Otp Registration Issue Fixed

- app/Http/Controllers/SuperAdmin/BoilerNewBrandController.php
> Upload Issue Fixing

- app/Http/Controllers/SuperAdmin/BoilerNewBrandController.php
- app/Http/Controllers/SuperAdmin/BoilerNewManualController.php
- app/Imports/BoilarManualImport.php
- resources/js/app/boiler-new-brands/list.js
- resources/js/app/boiler-new-manuals/list.js
- resources/views/app/superadmin/boiler_new_brands/show.blade.php
> Boiler Brand New Modification

- app/Http/Controllers/Api/BoilerBrandAndManualPageController.php
- app/Http/Controllers/BoilerBrandAndManualPageController.php
- app/Http/Controllers/SuperAdmin/BoilerNewBrandController.php
- app/Http/Controllers/SuperAdmin/BoilerNewManualController.php
- app/Models/BoilerNewBrand.php
- app/Models/BoilerNewManual.php
- database/migrations/2025_09_22_090310_add_logo_columns_to_boiler_new_brands_table.php
- resources/js/app/boiler-new-brands/crud.js
- resources/js/app/boiler-new-brands/list.js
- resources/views/app/boiler-brand-and-manual/index.blade.php
- resources/views/app/superadmin/boiler_new_brands/modal.blade.php
- resources/views/app/superadmin/boiler_new_brands/show.blade.php
- routes/api.php
> Boiler Brand & manual Updates

- app/Http/Controllers/Api/Auth/RegisteredUserController.php
- app/Http/Controllers/Api/BoilerBrandAndManualPageController.php
- app/Http/Controllers/Api/Customers/CustomerController.php
- app/Http/Controllers/Api/Jobs/JobsController.php
- app/Http/Controllers/Api/Records/RecordAndDraftController.php
- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/SuperAdmin/Settings/PricingPackageController.php
- app/Http/Controllers/SuperAdmin/Settings/SettingController.php
- app/Http/Controllers/SuperAdmin/Settings/UserSettingsController.php
- app/Http/Requests/PricingPackStoreRequest.php
- app/Http/Requests/PricingPackUpdateRequest.php
- app/Main/TopMenu.php
- app/Models/RegistrationOtp.php
- app/Models/UserOtp.php
- resources/js/app/superadmin/settings/api.js
- resources/js/app/superadmin/settings/pricing-package.js
- resources/js/app/superadmin/settings/registration-settings.js
- resources/js/app/superadmin/settings/settings.js
- resources/views/app/profile/index.blade.php
- resources/views/app/superadmin/settings/api.blade.php
- resources/views/app/superadmin/settings/index.blade.php
- resources/views/app/superadmin/settings/package/index-modals.blade.php
- resources/views/app/superadmin/settings/package/index.blade.php
- resources/views/app/superadmin/settings/sidebar.blade.php
- resources/views/app/superadmin/settings/sms-api.blade.php
- resources/views/app/superadmin/settings/user/index.blade.php
- routes/api.php
- routes/web.php
- vite.config.js
Profile + Super Admin Settings + API Modifications
> Profile + Super Admin Settings + API Modifications

- app/Http/Controllers/SuperAdmin/Settings/PricingPackageController.php
- app/Http/Controllers/SuperAdmin/Settings/UserSettingsController.php
> Missing Controller

- app/Http/Controllers/Api/Customers/CustomerJobsController.php
- app/Http/Controllers/Api/GlobalApiController.php
- app/Http/Controllers/Customers/CustomerJobsController.php
- app/Http/Controllers/Jobs/JobController.php
- app/Http/Controllers/SuperAdmin/Settings/JobCancelReasonController.php
- app/Http/Requests/JobCanceleRequest.php
- app/Http/Requests/JobCancellReasonRequest.php
- app/Http/Requests/JobStatusUpdateRequest.php
- app/Models/CancelReason.php
- app/Models/CustomerJob.php
- database/migrations/2025_09_29_104454_create_cancel_reasons_table.php
- database/migrations/2025_09_29_110555_add_multiple_columns_to_customer_jobs_table.php
- resources/js/app/customers/jobs/customer-jobs.js
- resources/js/app/jobs/jobs.js
- resources/js/app/superadmin/settings/cancel-reason.js
- resources/views/app/customers/jobs/index-modals.blade.php
- resources/views/app/jobs/index-modals.blade.php
- resources/views/app/superadmin/settings/cancel-reason/index-modals.blade.php
- resources/views/app/superadmin/settings/cancel-reason/index.blade.php
- resources/views/app/superadmin/settings/sidebar.blade.php
- routes/api.php
- routes/web.php
- vite.config.js
> Job Cancel Reason

- app/Http/Controllers/BoilerBrandAndManualPageController.php
- app/Models/BoilerNewManual.php
- resources/views/app/boiler-brand-and-manual/index.blade.php
- routes/web.php
Update manual download from S3
> Update manual download from S3

- app/Http/Controllers/Api/GlobalApiController.php
- app/Http/Controllers/BoilerBrandAndManualPageController.php
- routes/api.php
Get Option API Endpoint introduced
> Get Option API Endpoint introduced

- app/Http/Controllers/Api/BoilerBrandAndManualPageController.php
- app/Http/Controllers/BoilerBrandAndManualPageController.php
- routes/api.php
> Boiler Manual API

- app/Http/Controllers/Api/Customers/CustomerJobsController.php
- app/Http/Controllers/Api/Jobs/JobsController.php
- app/Http/Controllers/Customers/CustomerJobsController.php
- app/Http/Controllers/Jobs/JobController.php
- app/Http/Controllers/SuperAdmin/Settings/ReferralCodeController.php
- app/Http/Requests/ReferralCodeUpdateRequest.php
- resources/views/app/superadmin/settings/referral-code/index-modals.blade.php
Job REF && Referral Code Modifications
> Job REF && Referral Code Modifications

- app/Http/Controllers/Api/Customers/CustomerController.php
Customer Address Update issue fixed.
> Customer Address Update issue fixed.

- app/Http/Controllers/Api/Customers/CustomerController.php
- app/Http/Controllers/Api/Customers/CustomerJobAddressController.php
- app/Http/Controllers/Customers/CustomerController.php
- app/Http/Controllers/Customers/CustomerJobAddressController.php
- app/Http/Controllers/Drafts/RecordAndDraftController.php
- app/Http/Controllers/Jobs/JobController.php
- app/Http/Controllers/Records/NewRecordController.php
- app/Models/Customer.php
- app/Models/CustomerProperty.php
- database/migrations/2025_10_07_142818_add_is_primary_column_to_customer_properties_table.php
- database/migrations/2025_10_07_143046_drop_multiple_columns_from_customes_table.php
- resources/views/app/customers/edit-modal.blade.php
- resources/views/app/customers/job-address/edit-job-address.blade.php
Customer Address Modifications
> Customer Address Modifications
